{% set name = "scna-spice" %}
{% set version = "0.1.0" %}
{% set hash = "395302f9286b6b384de7bc3b518feeb103ca465b3549ed922de91c3bed7726bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install ortools==9.8.3296
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - medicc2 >=1.0
    - numpy
    - pandas
    - scipy
    - seaborn >=0.12
    - tqdm
    - fire
    - pyyaml
    - joblib
    - ortools 9.8.3296
    - importlib_resources >=5.0  # [py<39]

test:
  commands:
    - spice --help

about:
  home: https://bitbucket.org/schwarzlab/spice
  summary: SPICE; Selection Patterns In somatic Copy-number Events
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  description: |
    For more information see the accompanying publication "Kaufmann et al.
    Deciphering selection patterns of somatic copy-number events".
  dev_url: https://bitbucket.org/schwarzlab/spice

extra:
  recipe-maintainers:
    - tlkaufmann
